### ISSUE TITLE
[Suggestion] Can you maybe make the sky villages generate a lot higher in the sky?

### ISSUE THREAD

**Issue by Greg727** [SmartStreamLabs/Create-Sky-Village#2]
Whenever they generate in the world they always leave behind large amounts of darkness on the ground that spawns a lot of monsters, plus I think if the villages were higher it would look a lot better.

**Comment by SmartStreamLabs** [comment]
Hi, thank you for your feedback. the idea you have is already included in the next update! :) ( between 200& 300 spawn high )the update will appear on CurseForge within 3 days Support, Mei
